name: Flights Notifier

on:
  schedule:
    - cron: '0 7 * * *' # Every day at 07:00 UTC
  workflow_dispatch:

concurrency:
  group: flights-notifier
  cancel-in-progress: false

jobs:
  run-notifier:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    env:
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        Telegram__BotToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        Telegram__ChatId: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/Flights.Notifier/Flights.Notifier.csproj

      - name: Build
        run: dotnet build src/Flights.Notifier/Flights.Notifier.csproj --configuration Release --no-restore

      - name: Run Notifier
        run: dotnet run --project src/Flights.Notifier/Flights.Notifier.csproj --configuration Release
