name: Flights Notifier

on:
  schedule:
    - cron: '10 * * * *' # Every hour at :10 (UTC)
  workflow_dispatch:

concurrency:
  group: flights-notifier
  cancel-in-progress: false

jobs:
  run-notifier:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    env:
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore src/Flights.Notifier.Job/Flights.Notifier.Job.csproj

      - name: Build
        run: dotnet build src/Flights.Notifier.Job/Flights.Notifier.Job.csproj --configuration Release --no-restore

      - name: Run Notifier
        run: dotnet run --project src/Flights.Notifier.Job/Flights.Notifier.Job.csproj --configuration Release
